### ISSUE TITLE
Crash after window switch

### ISSUE THREAD

**Issue by MarcSchmitzer** [cnlpete/ttrss#155]
Since version 0.5.1, ttrss crashes after transitioning from one feed entry to another after the app was backgrounded.

Steps to reproduce:
1. Browse a feed.
2. Select "Open in Browser" on an item. Browser window opens in the foreground.
3. Return to ttrss through the "Running apps" screen.
4. Tap the "next entry" button (right arrow). ttrss transitions to the next feed entry an then closes.

This also *occasionally* happens without the window switch. I looked through the logs for clues as to what happened, but found nothing.

Platform: Nokia N9/MeeGo 1.2 Harmattan PR1.3

EDIT: I just reproduced this with 0.5.0. I think 0.4.7 was the last working version.
EDIT 2: Also reproducible by just swiping away from ttrss and returning or by pressing the power button and then returning to ttrss.

**Comment by cnlpete** [comment]
yes, i made a change to load a new page instead of replacing the content of the old one. This might use too much resources :(
i will try to have a look at this later tonight.

**Comment by MarcSchmitzer** [comment]
It's awesome that you fixed this so quickly. When are you planning on releasing 0.5.2?

I also wouldn't mind building it myself. Is there still any developer information for MeeGo around?

**Comment by MarcSchmitzer** [comment]
So, I've cherry-picked  2c589a0 onto the harmattan branch and built that. I can confirm that this seems to do the trick.

Thanks again for your work.

**Comment by cnlpete** [comment]
Sorry, i totally forgot about the harmattan build for 0.5.2. Glad you could build it yourself. i will try to build a new release from the current codebase next week.
