### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by onlygecko** [cnlpete/ttrss#157]
I was looking for tt-rss app for ubuntu touch (bq aquaris phone) and found on the ubuntu app store "tiny tiny rss" (https://uappexplorer.com/app/it.mardy.ttrss).

I'm not understanding why the version from the app store is a fork of this project? What's the reason for the fork? What repo should I address my ubuntu specific questions to?

**Comment by cnlpete** [comment]
Good question.
I simply do not have time to implement for ubuntu touch, plus i don't have the necessary equipment, nor the build sdk.
Mardy is the one who implemented the ui on top of my models and based on the sailfish ui (i guess).
Changes hopefully will make it back here, but ubuntu touch specific implementation will happen by mardy.

**Comment by mardy** [comment]
It's not really a fork (although github calls it that way), it's more like a development branch.

If questions are Ubuntu-specific, it's better to ask them in my "fork"'s bugtracker.

**Comment by onlygecko** [comment]
Thanks for clarifying. :-)
