### ISSUE TITLE
Margins in the settings page

### ISSUE THREAD

**Issue by valmar** [cnlpete/ttrss#161]
The articles look clean and professional with the new margins. I think the settings page should also have them (on Ubuntu Touch)

**Comment by cnlpete** [comment]
@mardy This only affects the ubuntu touch version, as far as i see

**Comment by mardy** [comment]
Indeed. @valmar , feel free to use https://github.com/mardy/ttrss to report Ubuntu-specific issues.

But you don't need to report this one again there, we can keep it here.
