### ISSUE TITLE
can't log in after upgrade to Sailfish Os 3.3.0.14

### ISSUE THREAD

**Issue by paolomi** [cnlpete/ttrss#173]
Hi, in Sailfish Os 3.3.0.14, ttrss can't log in ttrss server.  I tap on "Login" but nothing happens. Before upgrading, there were no problems. Here are the logs:

,---
| Sailfish OS 3.3.0.14 (Rokua)
'---
[nemo@Jolla ~]$ harbour-ttrss-cnlpete 
[D] unknown:0 - Using Wayland-EGL
[W] unknown:157 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:157: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:152 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:152: TypeError: Cannot read property 'backIndicatorDown' of null
[W] unknown:212 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:212: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:207 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:207: TypeError: Cannot read property 'forwardIndicatorDown' of null

Note: when i tap on "Login", it prints:

[W] unknown:207 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:207: TypeError: Cannot read property 'forwardIndicatorDown' of null
[W] unknown:207 - file:///usr/lib/qt5/qml/Sailfish/Silica/DialogHeader.qml:207: TypeError: Cannot read property 'forwardIndicatorDown' of null

**Comment by cnlpete** [comment]
That is weird

I will try to fix this at some point, but you should be able to manage by pressing enter on the keyboard after entering your password
Also you could set the AutoLogin in the settings, when you do not want to enter your details everytime ...

**Comment by paolomi** [comment]
Actually the AutoLogin in the settings was set on and after the upgrade it's stopped to work and tapping on "Login" didn't work.
But your tip is useful: pressing enter on the keyboard works! I'm dying of shame… Thanks a lot!

ps: i don't know if i have to close this bug report, I leave it up to you.

**Comment by cnlpete** [comment]
No, this is a real bug that deserves fixing :) I think i found the problem, so there will be a new version soon(tm)
