### ISSUE TITLE
Improved UI for HTTP authentication

### ISSUE THREAD

**Issue by cockroach** [cnlpete/ttrss#43]
It would be nice if the user / password fields could be used instead of putting the user name and password in the URL when using HTTP authentication. The way it is done at the moment the password is visible for a short while whenever the application is started.

Also: great app, thanks a lot!

**Comment by marxistvegan** [comment]
hey folks, this still has issues with the password int he server line if you use characters like @ in your password or username

**Comment by cnlpete** [comment]
implemented seperate http auth inputs
